services:
  - type: web
    name: game_theory_online
    runtime: python3
    buildCommand: pip3 install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 8 --timeout 0 GTO:app
    envVars:
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        value: "nějaký_tajný_klíč"